<?php
namespace AppBundle\Repository;


use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;
use AppBundle;
use AppBundle\Entity\Articles;
use AppBundle\Entity\Search;
/**
 * ArticlesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticlesRepository extends \Doctrine\ORM\EntityRepository
{
	public function getLatest($offset,$limit){ // fonction permettant d'afficher les actualité en partant de offset jusqu'à limite.
		
		$query = $this->getEntityManager()
		->createQuery( // On select a car on veut tout l'objet (avec les méthodes).
				'SELECT a FROM AppBundle:Articles a
				ORDER BY a.id DESC'
				);
		$query->setFirstResult($offset);
		$query->setMaxResults($limit);
		return $query->getResult();
		
	}
	
	public function getFromSearch($task){
		//$list=explode(' ',$task);
		$q=$this->getEntityManager()
		->createQuery("SELECT a FROM AppBundle:Articles a
				WHERE a.id LIKE '%$task%' OR a.title LIKE '%$task%' OR a.body LIKE '%$task%'
				ORDER BY a.id DESC
				");
		return $q->getResult();
		
	}
}